name: MiniRedis CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build -C Release --output-on-failure